#!/bin/bash
#
#
mosquitto_pub -t clock -h pi3.garf.de -m "clock color hour 131072"
mosquitto_pub -t clock -h pi3.garf.de -m "clock color minute 512"
mosquitto_pub -t clock -h pi3.garf.de -m "clock color second 65793"
mosquitto_pub -t clock -h pi3.garf.de -m "clock color tick 1"
